import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';
import { absoluteUrl, breadcrumbJsonLd, contentMetadata, jsonLd } from '@/lib/seo';

type Props = { params: Promise<{ date: string }> };
async function getFeature(date: string) { const supabase = await createClient(); return (await supabase.from('daily_features').select('*').eq('feature_date', date).eq('status', 'published').maybeSingle()).data; }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { date } = await params; const item = await getFeature(date); return item ? contentMetadata({ title: item.seo_title || `${item.verse_book} ${item.verse_chapter} — Verse of the Day`, description: item.seo_description || item.featured_verse, path: `/daily-features/${date}`, canonicalUrl: item.canonical_url, imageUrl: item.background_image_url, publishedAt: item.published_at || `${date}T00:00:00Z`, modifiedAt: item.updated_at, keywords: [item.focus_keyword, item.verse_book, 'verse of the day'].filter(Boolean), noIndex: item.no_index }) : { title: 'Verse not found' }; }
export default async function DailyFeatureDetail({ params }: Props) { const { date } = await params; const item = await getFeature(date); if (!item) notFound(); const url = `/daily-features/${date}`; const schema = { '@context': 'https://schema.org', '@type': 'Quotation', text: item.featured_verse, spokenByCharacter: item.verse_book, citation: `${item.verse_book} ${item.verse_chapter}`, url: absoluteUrl(url) }; return <div className="ggc-shell py-10 md:py-20"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(schema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(breadcrumbJsonLd([{ name: 'Home', path: '/' }, { name: 'Verse of the Day', path: '/daily-features' }, { name: date, path: url }])) }} /><Link href="/daily-features" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-forest"><ArrowLeft size={15} /> Daily verses</Link><article className="relative mt-8 overflow-hidden bg-brand p-8 text-white md:p-16">{item.background_image_url ? <img src={item.background_image_url} alt="" className="absolute inset-0 h-full w-full object-cover opacity-25" /> : null}<div className="relative mx-auto max-w-4xl text-center"><time className="text-xs font-bold uppercase tracking-[.18em] text-white/60">{date}</time><blockquote className="mt-8 font-serif text-4xl leading-tight md:text-6xl">“{item.featured_verse}”</blockquote><p className="mt-8 text-sm font-bold uppercase tracking-[.2em] text-amber3">{item.verse_book} {item.verse_chapter}</p></div></article></div>; }
