import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const sql = name => fs.readFileSync(new URL(`../supabase/migrations/${name}.sql`, import.meta.url), 'utf8');
await db.exec(`create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create table auth.users(id uuid primary key, email text, raw_user_meta_data jsonb);
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to anon, authenticated; grant execute on function auth.uid() to anon, authenticated;
create publication supabase_realtime;`);
await db.exec(sql('001_core_schema').replace('create extension if not exists pgcrypto;', ''));
await db.exec(sql('002_row_level_security'));
await db.exec(sql('006_complete_admin_and_analytics'));
await db.exec(sql('007_FIXED_notifications_and_usd'));
await db.exec(sql('011_community_engagement_google_theme'));
await db.exec(`create table api_secrets(key text primary key); alter table api_secrets enable row level security;
alter table donation_subscriptions add column stripe_customer_id text,add column stripe_subscription_id text;
alter table campaigns add column raised_amount_minor bigint not null default 0,add column donation_count bigint not null default 0,add column donor_count bigint not null default 0;`);
await db.exec(sql('015_one_page_giving'));
const admin = '11111111-1111-4111-a111-111111111111';
const member = '22222222-2222-4222-a222-222222222222';
await db.exec(`insert into auth.users values('${admin}','admin@test.test','{}'),('${member}','member@test.test','{}');
insert into admin_users(user_id,role) values('${admin}','super_admin');`);
await db.exec('set role anon');
await assert.rejects(db.exec(`insert into contact_messages(first_name,email,subject,message) values('Test','test@test.test','Hello','A contact message')`), /permission denied/);
await db.exec('reset role');
await db.exec(sql('016_restore_application_access'));
await db.exec(sql('016_restore_application_access'));
await db.exec(sql('017_analytics_overview'));
await db.exec(sql('017_analytics_overview'));
await db.exec('set role anon');
await assert.rejects(db.exec('select analytics_overview()'), /permission denied/);
await db.exec(`insert into contact_messages(first_name,email,subject,message) values('Test','test@test.test','Hello','A contact message');
insert into subscribers(email) values('subscriber@test.test');
select track_analytics('${member}','${member}','page_view','/','',null,null,null,null,'UTC','mobile');
select track_analytics('${member}','${member}','heartbeat','/');`);
await assert.rejects(db.exec('select * from contact_messages'), /permission denied/);
await assert.rejects(db.exec('select * from subscribers'), /permission denied/);
await assert.rejects(db.exec('select * from api_secrets'), /permission denied/);
await db.exec(`reset role; set role authenticated; select set_config('request.jwt.claim.sub','${admin}',false);`);
await db.exec(`insert into article_series(title,slug) values('New series','new-series'); update article_series set title='Edited';
update site_settings set ministry_name='Updated ministry';
select * from giving_daily; select giving_summary('USD',now()-interval '1 day',now());`);
assert.equal((await db.query('select count(*)::int n from contact_messages')).rows[0].n, 1);
assert.equal((await db.query('select page_views::int n from analytics_daily')).rows[0].n, 1);
assert.equal((await db.query('select count(*)::int n from active_sessions')).rows[0].n, 1);
assert.equal((await db.query('select device_type from analytics_events')).rows[0].device_type, 'mobile');
await db.exec(`insert into forum_posts(user_id,author_name,content,status) values('${admin}','Admin','Public post','approved');`);
const post = (await db.query('select id from forum_posts')).rows[0].id;
await db.exec(`select set_config('request.jwt.claim.sub','${member}',false);`);
await db.exec(`insert into content_reactions(user_id,content_type,content_id,reaction) values('${member}','post','${post}','like');`);
assert.equal((await db.query(`select like_count::int n from forum_posts where id='${post}'`)).rows[0].n, 1);
await db.exec(`delete from content_reactions where user_id='${member}'`);
assert.equal((await db.query(`select like_count::int n from forum_posts where id='${post}'`)).rows[0].n, 0);
await assert.rejects(db.exec("insert into article_series(title,slug) values('Forbidden','forbidden')"), /row-level security/);
assert.equal((await db.query('select count(*)::int n from contact_messages')).rows[0].n, 0);
assert.equal((await db.query('select count(*)::int n from analytics_events')).rows[0].n, 0);
assert.equal((await db.query("update site_settings set ministry_name='Forbidden' returning id")).rows.length, 0);
await assert.rejects(db.exec('select * from api_secrets'), /permission denied/);
assert.equal((await db.query("select analytics_overview() as data")).rows[0].data.page_views, 0);
await db.exec(`reset role;
insert into analytics_events(session_id,visitor_id,event_type,path,device_type,occurred_at)
select gen_random_uuid(),gen_random_uuid(),'page_view','/articles','desktop', now() - interval '1 hour' from generate_series(1,1200);
insert into analytics_events(session_id,visitor_id,event_type,path,device_type,occurred_at)
values(gen_random_uuid(),gen_random_uuid(),'page_view','/old','desktop',now()-interval '100 days');
set role authenticated; select set_config('request.jwt.claim.sub','${admin}',false);`);
const overview = (await db.query("select analytics_overview(30,'Africa/Kampala') as data")).rows[0].data;
assert.equal(overview.page_views, 1201);
assert.equal(overview.visitors, 1201);
assert.equal(overview.trend.length, 30);
assert.equal(overview.trend.reduce((total, day) => total + day.views, 0), 1201);
assert.deepEqual(overview.rankings.devices, [['desktop',1200],['mobile',1]]);
assert.equal(overview.history.length, 100);
assert.equal((await db.query("select analytics_overview(999,'Invalid/Zone') as data")).rows[0].data.trend.length, 30);
await db.exec(`reset role; update admin_users set role='content_manager' where user_id='${admin}';
set role authenticated; select set_config('request.jwt.claim.sub','${admin}',false);`);
await db.exec("insert into article_series(title,slug) values('Content manager edit','content-manager'); update impact_metrics set meals=42 where id=true;");
assert.equal((await db.query("update site_settings set ministry_name='Not allowed' returning id")).rows.length,0);
await db.exec(`reset role; update admin_users set role='viewer' where user_id='${admin}'; set role authenticated;`);
await assert.rejects(db.exec("insert into article_series(title,slug) values('No permission','viewer-write')"), /row-level security/);
await db.close();
console.log('PASS: analytics aggregates more than 1,000 events, fills empty days, respects dates and RLS, and handles invalid settings.');
console.log('PASS: repair is repeatable; contact, newsletter, likes, admin edits, giving and analytics work; member and anonymous restrictions remain enforced.');
