'use client';

import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, BookOpen, Loader2, LockKeyhole, ShoppingCart, Truck } from 'lucide-react';

type Ebook = { id: string; slug: string; title: string; author: string; cover_image_url: string; price_minor: number; shipping_amount_minor: number; currency: string; format: string; file_path: string | null };

export function EbookCheckout({ ebook, cancelled }: { ebook: Ebook; cancelled: boolean }) {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [phone, setPhone] = useState(''); const [isProcessing, setIsProcessing] = useState(false); const [error, setError] = useState('');
  const physical = ['Paperback', 'Hardcover'].includes(ebook.format);
  const totalMinor = Number(ebook.price_minor) + (physical ? Number(ebook.shipping_amount_minor || 0) : 0);
  const money = (minor: number) => minor === 0 ? 'Free' : `${ebook.currency} ${(minor / 100).toLocaleString('en-US', { minimumFractionDigits: 2 })}`;
  async function handleSubmit(event: React.FormEvent) { event.preventDefault(); setIsProcessing(true); setError(''); try { const response = await fetch('/api/stripe/ebook-checkout', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ebookId: ebook.id, buyerName: name, buyerEmail: email, buyerPhone: phone || undefined }) }); const result = await response.json(); if (!response.ok || !result.checkout_url) throw new Error(result.error || 'Checkout could not be opened.'); window.location.assign(result.checkout_url); } catch (problem) { setError(problem instanceof Error ? problem.message : 'Checkout could not be opened.'); setIsProcessing(false); } }
  return <div className="min-h-screen bg-cream py-16 md:py-24"><div className="ggc-shell"><Link href="/ebooks" className="mb-8 inline-flex items-center gap-2 text-sm font-semibold text-forest hover:underline"><ArrowLeft size={16} /> Back to ebooks</Link>{cancelled ? <div className="mb-6 border border-amber/30 bg-amber/10 p-4 text-sm text-ink2">Checkout was cancelled. Your card was not charged and your order remains incomplete.</div> : null}<div className="grid gap-8 lg:grid-cols-[1fr_auto]">
    <section className="border border-border bg-surface p-6 shadow-shadow"><h1 className="mb-6 font-serif text-2xl">Order Summary</h1><div className="flex items-center gap-4 border-b border-border pb-6"><div className="aspect-[3/4] w-24 overflow-hidden bg-[linear-gradient(145deg,#142b3f,#234b66)] p-3">{ebook.cover_image_url ? <img src={ebook.cover_image_url} alt={`${ebook.title} cover`} className="h-full w-full object-contain" /> : <div className="flex h-full items-center justify-center"><BookOpen size={32} className="text-white/30" /></div>}</div><div className="flex-1"><h2 className="font-serif text-xl leading-tight">{ebook.title}</h2><p className="mt-1 text-sm text-ink3">by {ebook.author}</p><p className="mt-2 text-[.58rem] font-bold uppercase tracking-[.17em] text-amber">{ebook.format}</p></div><p className="font-serif text-2xl text-forest">{money(ebook.price_minor)}</p></div><div className="mt-6 flex items-start gap-3 border border-border bg-cream2 p-4">{physical ? <Truck size={20} className="mt-0.5 shrink-0 text-amber" /> : <BookOpen size={20} className="mt-0.5 shrink-0 text-amber" />}<div><p className="text-sm font-bold text-ink2">{physical ? 'Physical delivery' : 'Protected digital download'}</p><p className="mt-1 text-xs leading-5 text-ink3">{physical ? 'Stripe will collect your delivery address securely. The order will appear in Admin for fulfillment.' : 'After Stripe confirms payment, your private download appears on the success page and is also emailed when Resend is configured.'}</p></div></div><div className="mt-6 space-y-3 border-t border-border pt-6"><div className="flex justify-between text-sm"><span className="text-ink3">Subtotal</span><span className="font-semibold">{money(ebook.price_minor)}</span></div>{physical ? <div className="flex justify-between text-sm"><span className="text-ink3">Shipping</span><span className="font-semibold">{money(ebook.shipping_amount_minor || 0)}</span></div> : null}<div className="flex justify-between text-lg font-bold"><span>Total</span><span className="font-serif text-forest">{money(totalMinor)}</span></div></div></section>
    <section className="w-full border border-border bg-surface p-6 shadow-shadow lg:w-[420px]"><h2 className="mb-6 font-serif text-2xl">Checkout Details</h2><form onSubmit={handleSubmit} className="space-y-5"><label className="grid gap-2 text-xs font-bold uppercase tracking-[.08em] text-ink2">Full name <span className="text-red-500">*</span><input className="field" value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" required /></label><label className="grid gap-2 text-xs font-bold uppercase tracking-[.08em] text-ink2">Email address <span className="text-red-500">*</span><input type="email" className="field" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" required /><span className="font-normal normal-case tracking-normal text-ink3">Your receipt and download link will use this address.</span></label><label className="grid gap-2 text-xs font-bold uppercase tracking-[.08em] text-ink2">Phone <span className="font-normal normal-case tracking-normal text-ink3">Optional</span><input className="field" value={phone} onChange={(event) => setPhone(event.target.value)} autoComplete="tel" /></label><div className="border-t border-border pt-5"><div className="flex gap-3 bg-cream2 p-4"><LockKeyhole size={19} className="mt-0.5 shrink-0 text-forest" /><div><p className="text-sm font-bold">Payment stays on Stripe</p><p className="mt-1 text-xs leading-5 text-ink3">Card numbers never enter or pass through the GGChrist website. Stripe securely collects and processes payment.</p></div></div></div>{error ? <div className="border border-red-200 bg-red-50 p-4 text-sm text-red-700" role="alert">{error}</div> : null}<button type="submit" disabled={isProcessing} className="btn-nav btn-amber w-full">{isProcessing ? <Loader2 size={16} className="animate-spin" /> : <ShoppingCart size={14} />}{isProcessing ? 'Opening secure checkout…' : totalMinor === 0 ? 'Get this ebook' : `Continue to Stripe · ${money(totalMinor)}`}</button><p className="text-center text-xs text-ink3"><span className="font-semibold">Secure payment</span> powered by Stripe.</p></form></section>
  </div></div></div>;
}
