import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ShoppingCart, Star } from 'lucide-react';
import { createClient } from '@/lib/supabase/server';
import { absoluteUrl, breadcrumbJsonLd, contentMetadata, jsonLd } from '@/lib/seo';

type Props = { params: Promise<{ slug: string }> };
async function getEbook(slug: string) { const supabase = await createClient(); return (await supabase.from('ebooks').select('*').eq('slug', slug).eq('status', 'published').maybeSingle()).data; }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const item = await getEbook(slug); return item ? contentMetadata({ title: item.seo_title || item.title, description: item.seo_description || item.description, path: `/ebooks/${slug}`, canonicalUrl: item.canonical_url, imageUrl: item.cover_image_url, publishedAt: item.published_at, modifiedAt: item.updated_at, author: item.author, keywords: [item.focus_keyword, item.category, ...(item.tags || [])], noIndex: item.no_index }) : { title: 'Ebook not found' }; }
export default async function EbookDetail({ params }: Props) {
  const { slug } = await params; const item = await getEbook(slug); if (!item) notFound();
  const price = (Number(item.price_minor || 0) / 100).toFixed(2);
  const schema = { '@context': 'https://schema.org', '@type': 'Book', name: item.title, description: item.description, image: item.cover_image_url, author: { '@type': 'Person', name: item.author }, inLanguage: item.language, numberOfPages: item.pages, bookFormat: item.format, url: absoluteUrl(`/ebooks/${item.slug}`), offers: { '@type': 'Offer', price, priceCurrency: item.currency || 'USD', availability: 'https://schema.org/InStock', url: absoluteUrl(`/checkout?ebook=${item.id}`) }, aggregateRating: Number(item.review_count) > 0 ? { '@type': 'AggregateRating', ratingValue: Number(item.rating), reviewCount: Number(item.review_count) } : undefined };
  return <div className="ggc-shell py-10 md:py-16"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(schema) }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: jsonLd(breadcrumbJsonLd([{ name: 'Home', path: '/' }, { name: 'Ebooks', path: '/ebooks' }, { name: item.title, path: `/ebooks/${item.slug}` }])) }} /><Link href="/ebooks" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.13em] text-forest"><ArrowLeft size={15} /> Ebook library</Link><article className="mt-8 grid gap-8 border border-border bg-surface p-7 md:grid-cols-[300px_1fr] md:p-12">{item.cover_image_url ? <img src={item.cover_image_url} alt={`${item.title} book cover`} className="w-full object-cover shadow-shadow" /> : <div className="aspect-[3/4] bg-brand" />}<div><p className="section-kicker">{item.category || 'Christian ebook'} · {item.format}</p><h1 className="mt-5 font-serif text-5xl leading-none md:text-7xl">{item.title}</h1>{item.subtitle ? <p className="mt-5 text-xl text-ink3">{item.subtitle}</p> : null}<p className="mt-4 font-semibold text-forest">By {item.author}</p>{Number(item.rating) > 0 ? <p className="mt-3 inline-flex items-center gap-1 text-sm text-amber"><Star size={15} fill="currentColor" /> {Number(item.rating).toFixed(1)} ({item.review_count} reviews)</p> : null}<p className="mt-8 whitespace-pre-wrap text-base leading-8 text-ink3">{item.description}</p><div className="mt-8 flex flex-wrap items-center gap-5 border-t border-border pt-6"><span className="font-serif text-3xl text-forest">{item.currency || 'USD'} {price}</span><Link href={`/checkout?ebook=${item.id}`} className="btn-nav btn-amber"><ShoppingCart size={15} /> Buy ebook</Link></div></div></article></div>;
}
